# Generated by Django 5.2.1 on 2025-06-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_book_language_case_insensitive_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
    ]
